### ISSUE TITLE
Update version in Cocoapods trunk

### ISSUE THREAD

**Issue by olejnjak** [WorldDownTown/Benchmark#2]
Hi, 

would it be possible to push new podspec to Cocoapods trunk so we don't have to target git in our Podfiles? 

Thanks

**Comment by WorldDownTown** [comment]
@olejnjak I'm sorry for being late to do this task.
I updated podspec and uploaded to trunk.
https://cocoapods.org/pods/Benchmark

**Comment by olejnjak** [comment]
Good!
